pagopa/io-app-design-system

src/components/alert/Alert.tsx, src/components/alert/index.tsx, src/components/index.tsx
This PR implements the Alert component
=> [IOPLT-72] Adds the Alert component

src/components/checkbox/CheckboxLabel.tsx, src/components/switch/SwitchLabel.tsx, src/functions/haptic-feedback/hapticFeedback.ts, src/functions/haptic-feedback/index.ts, src/functions/index.ts, src/index.tsx
This PR wraps up the react-native-haptic-feedback inside the DS library and exports it
=> [IOPLT-75] Defines a single point definition for haptic feedback function

src/components/typography/CTA.tsx, src/components/typography/__test__/__snapshots__/typography.test.tsx.snap, src/components/typography/__test__/typography.test.tsx, src/components/typography/index.tsx
Migrating CTA component from IO-app
- CTA
=> [IOPLT-108] Migrating CTA component from io-app

example/src/pages/FooterWithButton.tsx, src/components/badge/Badge.tsx, src/components/badge/__test__/__snapshots__/badge.test.tsx.snap, src/components/buttons/IconButtonSolid.tsx, src/components/buttons/__test__/__snapshots__/button.test.tsx.snap, src/components/listitems/ListItemIDP.tsx, src/components/listitems/__test__/__snapshots__/listitem.test.tsx.snap, src/components/tag/Tag.tsx, src/components/textInput/TextInputBase.tsx
This PR completes the migration of fonts for legacy visualization support
Check everythings ok in the example app
=> fix: Migrates missing components from the list on legacy font usage

example/src/pages/Modules.tsx, src/components/modules/ModuleIDP.tsx
This PR removes the unused `urlLogoIDP` prop from the `ModuleIDP` component
- Remove `urlLogoIDP` prop
N/A
=> Remove unused `ModuleIDP` prop

src/components/listitems/ListItemSwitch.tsx, src/components/modules/ModulePaymentNotice.tsx
This PR exports types of `ListItemSwitch` and `ModulePaymentNotice` components
- Export type(s) of `ListItemSwitch`
- Export type of `ModulePaymentNotice`
N/A
=> Export types of `ListItemSwitch` and `ModulePaymentNotice` components

example/src/pages/HeaderSecondLevel.tsx, src/components/layout/HeaderFirstLevel.tsx, src/components/layout/HeaderSecondLevel.tsx
This PR inverts the order of the three possible actions in order to properly handle possible integration and extensions through wrapping components in the main app.
Check the example app for further tests
=> [IOPLT-194] Inverting the header actions order

example/src/pages/FooterWithButton.tsx, src/components/layout/BlockButtons.tsx, src/components/layout/FooterWithButtons.tsx
This PR patches `FooterWithButtons` component to properly handle sticky cases
=> fix: patch FooterWithButtons component

package.json, src/components/listitems/ListItemSwitch.tsx, src/components/switch/NativeSwitch.tsx, yarn.lock
This PR improves the accessibility of the ListItemSwitch to let it read on the Switch toggle the label and the status on native APIs
- Handle `ListItemSwitch` accessibility scenarios
- Extend `NativeSwitch` props
Test on real device.
=> fix: [IOPLT-196] Fixes ListItemSwitch accessibility

src/components/loadingSpinner/LoadingSpinner.tsx
This PR adds minor improvements to the `LoadingSpinner` component.
- Slow down the animation a little bit
- Decrease the `stroke` value based on size
There's no `Loaders` page. Add it to one random page of the example app.
=> [IOAPPFD0-176] Improvements to the `LoadingSpinner`

example/src/pages/TextInputs.tsx, src/components/banner/Banner.tsx, src/components/banner/__test__/__snapshots__/banner.test.tsx.snap
This PR aims to fix the accessibility on the Banner component
- Changes the accessibility attributes on Banner component
Check how voiceover intercepts each element of a banner
=> [IOPLT-195] Fixes the accessibility issue preventing to intercept the closing button on banner

example/src/pages/TextInputs.tsx, src/components/textInput/TextInputBase.tsx
This PR specifies the font name on the label component to prevent errors on main app representation
- Specifies font on Text label
Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
=> [IOPLT-203] Specifies the label font on TextInput component

src/components/modules/ModulePaymentNotice.tsx
This PR enhances the ModulePaymentNotices
- "inprogress" status
- padding on the subtitle label
- two lines subtitle label
=> [IOCOM-641] Enhancements on ModulePaymentNotices

example/src/pages/Modules.tsx, src/components/listitems/__test__/__snapshots__/listitem.test.tsx.snap, src/components/modules/ModuleIDP.tsx, src/components/modules/ModulePaymentNotice.tsx, src/components/modules/PressableModuleBase.tsx, src/components/modules/hooks/useModuleSpringAnimation.ts, src/components/modules/index.tsx, src/core/IOStyles.ts, src/stories/ModuleIDP.stories.tsx
This PR implements the `PressbaleModuleBase` component refactoring part of the code on `ModuleIDP` and `ModulePaymentNotice`
- Creates `PressbaleModuleBase` 
- Refactors `ModuleIDP` and `ModulePaymentNotice`
Check the example app on Modules Section
=> [IOPLT-139] Pressable module base component

example/src/pages/ListItem.tsx, src/components/listitems/ListItemInfo.tsx, src/components/listitems/__test__/__snapshots__/listitem.test.tsx.snap
This PR refines the ListItemInfo component to prevent accessibility and action implementation issues
- Action node is controlled inside the component
- Accessibility fix to only read action when provided
Check on the example app
https://github.com/pagopa/io-app-design-system/assets/3959405/7414e305-00d7-4bbd-ba43-a07c77f8a697
=> [IOPLT-223] Refinement on ListItemInfo component

example/src/pages/ListItem.tsx, src/components/listitems/ListItemInfo.tsx
Extends `ListItemInfo` right element to support badge component
Check the example app
=> chore: Extends ListItemInfo with badge variant

example/src/pages/ListItem.tsx, src/components/listitems/ListItemNav.tsx
add badge props and hide chevron icon on listItemNav
- Add badge component to listItemNav 
- Handle possible hiding of chevron icon
Check the listItem page of example app
=> [IOPLT-238] Refinement ListItemNav with Badge 

example/src/pages/Logos.tsx, src/components/avatar/Avatar.tsx, stories/foundation/avatar/Avatar.stories.ts
This PR reintroduces the logic to handle multiple images into the avatar component in order to let the dev specify a possible fallback.
In case none of the uri's working the placeholder icon is rendered
- Avatar Component
- Example page representation
- Adds the Storybook example
Check example app / storybook
=> feat: [IOPLT-340] Let Avatar component handle multiple images

src/components/alert/Alert.tsx
This PR changes the View Ref type to optional in the Alert component.
- Input View Ref is now optional
=> [chore] Optional view ref type for Alert view

src/components/listitems/ListItemCheckbox.tsx, src/components/switch/NativeSwitch.tsx
This PR fixes accessibility behaviour on `ListItemCheckbox`.
Extends props on NativeSwitch
- ListItemCheckbox - fixes accessibility handling
- NativeSwitch - extends native props support
Accessibility should work properly on both components
=> [IOPLT-381] Fix accessibility attributes on ListItemCheckbox

src/core/IOColors.ts, src/core/IOThemeContextProvider.tsx
This PR adds a theme for legacy colors handler
- IOThemeContext
- Add  new theme `appBackground-accent` variable
Adds a new color theme for legacy view
=> chore: Legacy color theme

.eslintrc.js, package.json, src/components/avatar/Avatar.tsx, src/components/avatar/__test__/__snapshots__/avatar.test.tsx.snap, src/components/checkbox/AnimatedCheckbox.tsx, src/components/checkbox/AnimatedMessageCheckbox.tsx, src/components/checkbox/CheckboxLabel.tsx, src/components/image/Image.tsx, src/components/listitems/ListItemNav.tsx, src/components/listitems/ListItemRadio.tsx, src/components/listitems/__test__/__snapshots__/listitem.test.tsx.snap, src/components/modules/ModuleIDP.tsx, src/components/radio/AnimatedRadio.tsx, src/components/radio/RadioButtonLabel.tsx, src/components/switch/AnimatedSwitch.tsx, src/components/switch/SwitchLabel.tsx, src/core/IOStyles.ts, yarn.lock
This PR adds the `eslint-plugin-react-native-a11y` ([official repo](https://github.com/FormidableLabs/eslint-plugin-react-native-a11y) from [FormidableLabs](https://github.com/FormidableLabs)) to enforce accessibility.
- Add `eslint-plugin-react-native-a11y` as dev dependency
- Enable all rules in the `eslintrc` file
N/A
=> [IOAPPX-268] Add `eslint-plugin-react-native-a11y` to enforce accessibility

src/components/avatar/Avatar.tsx
This PR adds local image source as imageSource on avatar component
- Avatar component props
Adding a local image import on source prop should work fine
=> chore: let avatar component render local Image Require

example/src/pages/Advice.tsx, src/components/banner/Banner.tsx, src/components/banner/__test__/banner.test.tsx, stories/components/banner/Banner.stories.tsx
This PR marks as optional the `viewRef` property from the `Banner` component.
- `viewRef` property is now optional
Check that everything compiles and runs properly.
=> [chore] Optional viewRef for Banner

src/components/listitems/ListItemSwitch.tsx
This PR fixes a bad import on ListItemSwitch.
- Relative-from-folder path import on listItemWithSwitch
=> [chore] Fix for WithTestID import on SwtichListItem

src/components/textInput/TextInputBase.tsx
Fixes the test id not propagating to its children components on TextInputVariants
- TextInputBase
N/A
=> fix: properly propagate testID to children

src/components/typography/BaseTypography.tsx, src/components/typography/Body.tsx, src/components/typography/BodyMonospace.tsx, src/components/typography/ButtonText.tsx, src/components/typography/Caption.tsx, src/components/typography/Chip.tsx, src/components/typography/Factory.tsx, src/components/typography/H1.tsx, src/components/typography/H2.tsx, src/components/typography/H3.tsx, src/components/typography/H4.tsx, src/components/typography/H5.tsx, src/components/typography/H6.tsx, src/components/typography/Hero.tsx, src/components/typography/Label.tsx, src/components/typography/LabelHeader.tsx, src/components/typography/LabelLink.tsx, src/components/typography/LabelSmall.tsx, src/components/typography/LabelSmallAlt.tsx
This PR adds ref attribute to all typographical components
- Changed BaseTypography, useTypographyFactory, all typographical components 
N/A
=> [IOPLT-485] Propagate ref attribute to all Typographic components

src/components/typography/H4.tsx, src/components/typography/__test__/__snapshots__/typography.test.tsx.snap
This PR fixes the value of the H4 line height.
- Update `H4` typographic style
N/A
=> [IOAPPX-298] Fix the value of the H4 line height

example/src/pages/SearchCustom.tsx, src/components/searchInput/SearchInput.tsx
This PR adds `onCancel` prop on `SearchInput` component.
2. Go to the **SearchCustom** screen
=> [IOPAE-1235] Add `onCancel` prop on `SearchInput`

example/src/pages/Accordion.tsx, src/components/accordion/AccordionItem.tsx, stories/components/accordion/RawAccordion.stories.tsx
This PR removes the mandatory `id` prop from `AccordionItem`
- Remove `id` prop
N/A
=> [IOAPPX-323] Remove mandatory `id` prop from `AccordionItem`

jest.config.js, package.json
This PR adds `prepare` script in the `package.json` file
- updated the `package.json`
- added `modulePathIgnorePatterns` in `jest.config.js`
Checks should pass correctly
=> chore: Add `prepare` script

example/package.json, example/yarn.lock, package.json, yarn.lock
This PR updates reanimated version to be the same spec as main io-app
Check all the animations to work properly
=> chore: bumps reanimated version to be updated with the main app dependency

src/components/contentWrapper/ContentWrapper.tsx
This PR adds `testID` prop to the `ContentWrapper` component.
N/A
=> [IOAPPX-400] Add `testID` to `ContentWrapper`

example/src/pages/Advice.tsx, src/components/featureInfo/FeatureInfo.tsx, src/components/typography/ComposedBodyFromArray.tsx, src/components/typography/__test__/ComposedBodyFromArray.test.tsx, src/components/typography/__test__/__snapshots__/ComposedBodyFromArray.test.tsx.snap, src/components/typography/index.tsx
This PR migrates `ComposedBodyFromArray` from `io-app`
- Add component to the codebase and its relative tests
- Add example to **Advices** page (`FeatureInfo`)
N/A
=> [IOAPPX-410] Migrate `ComposedBodyFromArray` from `io-app`

src/components/typography/H2.tsx, src/components/typography/__test__/__snapshots__/typography.test.tsx.snap
- Decrease the `H2` line-height value
- Update relative tests
N/A
=> Decrease `H2` line height value

src/components/typography/IOText.tsx, src/utils/accessibility.ts, src/utils/fonts.ts
This PR enables dynamic component scaling in the legacy UI, as well.
- Remove `isExperimental` condition
Check if **Selection** components have scaled sizes in the legacy UI (new DS disabled)
=> [IOAPPX-451] Enable dynamic component scaling in the legacy UI

example/src/pages/TextInputs.tsx, src/components/textInput/TextInputValidation.tsx, src/utils/types.ts
This pull request is adding a new type definition, updating the `TextInputValidation` component to use this new type
- Added a new type definition `TextInputValidationRefProps` to represent the shape of the ref object used in `TextInputValidation`
N/A
=> refactor: global text input validation ref prop type

src/components/tabs/TabItem.tsx
This PR adds the `ref` to the `TabItem` component, it will be useful to have component references and set the accessibility focus on it.
- Wrapped the `TabItem` component with the usage of `forwardRef`
=> chore: [IOBP-1196] Added ref to `TabItem` component

src/components/searchInput/SearchInput.tsx
This PR improves the accessibility of the `SearchInput` component. 
- added `importantForAccessibility` prop to make the input field inaccessible when the component is pressable. This change ensures that the input is not announced by SR when the component is intended to be used as a button.
=> chore: [IOPAE-1728] Improve accessibility on `SearchInput` component

src/components/badge/Badge.tsx
This pull request is adding an `accessible` prop to the `Badge` type and updating the component to use this new prop
- Updated the `View` component within `Badge` to use the new `accessible` prop instead of a hardcoded value.
N/A
=> chore(Badge): Add `accessible` prop

example/src/pages/TextInputs.tsx, src/utils/textInput/index.ts, src/utils/types.ts
This pull request introduces support for handling IBAN input types in the text input components
- Extended the `InputType` type to include "iban" as a valid input type
- Added a case for the `iban` input type in the `getInputPropsByType` function, including formatting and input properties specific to IBAN
Check the example in `TextInputs` section
https://github.com/user-attachments/assets/873ebed5-dc74-4499-a170-06b70f288e01
=> feat(TextInput): iban formatter

src/components/buttons/ButtonLink.tsx
This PR aims to extend the accessibility role of the ButtonLink component
- Adds accessibilityRole prop on ButtonLink component
Nothing has been changed on behaviour
=> feat:[IOPLT-1023] Extends ButtonLink accessibilty roles

src/components/listitems/__test__/__snapshots__/listitem.test.tsx.snap, src/components/skeleton/IOSkeleton.tsx
This pull request updates `IOSkeleton` component refactoring the animation logic
- Replace `reanimated` with default `react-native` api 
- Test `IOSkeleton` in both Android and iOS device
- Ensure that there are no frame drops
https://github.com/user-attachments/assets/0c00fce7-1f29-4647-9f4e-3d02f92c7ead
=> refactor(`IOSkeleton`): replace `reanimated` with native `Animated` APIs

example/src/pages/Loaders.tsx, src/components/listitems/ListItemSwitch.tsx, src/components/loadingSpinner/LoadingSpinner.tsx, src/components/modules/ModuleAttachment.tsx, src/components/modules/ModuleCredential.tsx, src/components/otpInput/OTPInput.tsx, src/components/progressLoader/ProgressLoader.tsx
This PR improves accessibility and performance of the loaders and adds support for dark mode.
- **`LoadingSpinner`**
- Add dark mode support
- Partial refactoring to add a cleanup function to the animation to prevent memory leaks
- Remove color set in `Module…` and `ListItem…` components because it's already baked in the original component
- **`ProgressLoader`**
- Add dark mode support
- Add `accessibilityRole` and `accessibilityValue` to improve the accessibility of the component
https://github.com/user-attachments/assets/76dbe347-3f4a-474a-ac28-46acb345cf49
Run the example app. Go to the **Loaders** page. Enable/Disable dark mode for testing purposes
=> chore: [IOPLT-971] Improve accessibility and performance of the loaders + Add support for dark mode

example/ios/ExampleApp.xcodeproj/project.pbxproj, example/ios/Podfile.lock
This PR updates iOS related files (`Podfile.lock`, `*.pbxproj`) that were erroneously released with PR #437
N/A
=> fix: [IOPLT-933] Fix iOS related files (`Podfile.lock`, `*.pbxproj`) after `ExampleApp` upgrade to `0.75`

example/src/pages/Buttons.tsx, example/src/pages/ListItem.tsx, src/components/listitems/ListItemHeader.tsx
This PR add an optional `description` to `ListItemHeader` component
- Add optional description if present
- Add to example app a `ListItemHeader` with a description
Check in the example app the `ListItemHeader` with the description
=> feat: [SIW-2201]  Add optional description to ListItemHeader

src/components/searchInput/SearchInput.tsx
This PR adds dark mode support for `SearchInput`.
- Add themed styles to the `SearchInput` component
https://github.com/user-attachments/assets/3fcb98f5-9ba6-49dd-814f-e16770f36275
2. Go to the **Search Input** page
=> chore: [IOPLT-970] Add dark mode support for `SearchInput`

src/components/buttons/IOButton/IOButton.tsx, src/components/buttons/IOButton/__test__/__snapshots__/IOButton.test.tsx.snap, src/components/buttons/IOButton/styles.tsx
Fixe issues on updating buttons when the color variant has been update as a prop
=> fix: [IOPLT-000] Fix `IOButton` updates

src/components/banner/Banner.tsx
This PR refactors Banner component handling of the ref in favour of the forwardRef function of React.
- Banner component
Ref should be properly handled as always
=> refactor: Remove ref from prop in favour of forwardRef
