.github/actions/setup/action.yml
.github/workflows/checks.yml
package.json
src/components/typography/BaseTypography.tsx
src/components/typography/Body.tsx
src/components/typography/Factory.tsx
src/components/typography/H1.tsx
src/components/typography/H2.tsx
src/components/typography/H3.tsx
src/components/typography/H4.tsx
src/components/typography/H5.tsx
src/components/typography/H6.tsx
src/components/typography/Label.tsx
src/components/typography/LabelSmall.tsx
src/components/typography/Link.tsx
src/components/typography/Monospace.tsx
src/components/typography/__test__/__snapshots__/typography.test.tsx.snap
src/components/typography/__test__/typography.test.tsx
src/components/typography/common.tsx
src/utils/fonts.ts
src/utils/types.ts
yarn.lock

Migrating all the typography components from the io-app.
- BaseTypograhy
- Body
- Factory
- H1
- H2
- H3
- H4
- H5
- H6
- Label
- LabelSmall
- Link
- Monospace

[IOPLT-64] Migrating typography components from io-app

---

src/components/listitems/ListItemTransaction.tsx
src/components/typography/H5.tsx

This PR adds ellipsis to `ListItemTransaction` when the title is too long;
- Added `numberOfLines={2}` to the title of `ListItemTransaction`;
- Change title typography of `ListItemTransaction` with H5 using 14px;
Open the section `ListItem` and check that the ListItemTransaction with a long text has an ellipsis to the and

chore: [IOBP-155] Add ellipses if text too long into `ListItemTransaction`

---

example/src/pages/Buttons.tsx
src/components/buttons/ButtonLink.tsx
src/components/buttons/ButtonOutline.tsx
src/components/buttons/ButtonSolid.tsx
src/components/typography/ButtonText.tsx
src/components/typography/LabelLink.tsx
src/components/typography/__test__/__snapshots__/typography.test.tsx.snap

This PR fixes the following visual regressions:
* `LabelLink` component: it didn't have the correct color when experimental DS is off
* Legacy style of the `ButtonSolid` contrast variant: it used the `blueIO` colour instead of the classic blue
* Both `ButtonSolid` and `ButtonOutline` had wrong icon sizes (too big for the legacy variant)
N/A

[IOAPPFD0-154] Fix UI regressions affecting `Button…` and `LabelLink` components

---

src/components/pictograms/Pictogram.tsx

This PR replace the old max Pictogram scale size from value `240` to value `180`
- Edited type `IoPictogramSizeScale` into file `Pictogram.tsx` replacing the old value;

chore: [IOBP-265] Change max size scale of a Pictogram to `180`

---

example/src/pages/Selection.tsx
src/components/listitems/ListItemSwitch.tsx

This PR refactors the `ListItemSwitch` component to handle payment logos.
- Add the new `paymentLogo` prop
- Make the component more robust, avoiding jump between different states (switch → loading indicator → badge)
2. Go to the **Selection** page

[IOAPPFD0-157] Refactor `ListItemSwitch` to handle payment logos

---

example/src/pages/Selection.tsx
src/components/radio/RadioGroup.tsx

This PR does exactly what the title says.
- Rename type from `NewRadioItem` to `RadioItem`
N/A

[IOAPPFD0-164] Rename type from `NewRadioItem` to `RadioItem`

---

src/components/listitems/ListItemTransaction.tsx

This PR fixes an accessibility issue with the `ListItemTransaction` where, on iOS, VoiceOver reads time and amount numbers as one number (eg: `23:15 45,67€` reads "23" and "1.545,67€").
The fix consists in setting to `false` the `accessible` prop in the parent component. Now the `accessible` prop is passed from the parent component, default is `false`.
- [src/components/listitems/ListItemTransaction.tsx](https://github.com/pagopa/io-app-design-system/pull/91/files#diff-e161c812707e7a718a116a2c9a28e50d9d46a9956ffa18d7950aafe270570ed9): added the `accessible` prop in the parent component.
Use VoiceOver on iOS to read an `ListItemTransaction` component.
This issue should be tests on physical devices since it cannot be reproduced on simulators.

[IABT-1490] Fix amount text a11y in `ListItemTransaction`

---

src/components/loadingSpinner/LoadingSpinner.tsx

This PR adds some new A11Y related props to the `LoadingSpinner`. It also slightly refactor the component removing the `stroke` prop.
- Add optional `accessibilityHint` and `accessibilityLabel` props
- Remove `stroke` prop, replacing it with a `strokeMap` based on size of the loading spinner
N/A

[IOAPPFD0-173] Add A11Y related props to the `LoadingSpinner`

---

src/components/listitems/ListItemSwitch.tsx

This PR replaces the old `ActivityIndicator` with the new `LoadingSpinner` in the `ListItemSwitch` component.
- Replace `Activity Indicator`
2. Go to the **Selection** page

Add `LoadingSpinner` to the `ListItemSwitch`

---

example/src/pages/TextInputs.tsx
src/components/textInput/TextInputBase.tsx

This PR adds the ability to pass `autoCapitalize` prop to `TextInput` component
- Added `autoCapitalize` to `RNTextInputProps` type
Use a TextInput component and pass `autoCapitalize` to the `textInputProps`. Check that the casing is correctly handled by the component.

chore: add `autoCapitalize` to `RNTextInputProps`

---

example/src/pages/ListItem.tsx
src/components/listitems/ListItemNav.tsx

This PR introduces a new `ListItemNav` prop: `paymentLogo` which allows to show an icon on the left side which is a payment logo instead of IOIcons.
- Added a new prop `paymentLogo` into component
Open the example app and navigate to "List item" section and you should see a list item nav with a bancomat pay logo on the left

chore: [IOBP-352] Add paymentLogo prop into `ListItemNav`

---

src/components/textInput/TextInputBase.tsx

This PR adds the `autoCorrect` prop to `TextInput` component
- [src/components/textInput/TextInputBase.tsx](https://github.com/pagopa/io-app-design-system/compare/add-auto-correct-prop-to-text-input?expand=1#diff-4c896698eb784ea23eeccb310d573873e1d296d505cf84c166d59f61be6e3968): added `autoCorrect` in the Pick type
On a `TextInput` component, try to pass the `autoCorrect` prop in the `textInputProps` and check if the component has the expected behavior.

chore: add `autoCorrect` prop to `TextInput` component

---

example/src/pages/Badges.tsx
src/components/badge/Badge.tsx

This PR implements the badge variant for outlined representation
- Changes Badge component
Check the example app under `Badges & Tags` screen

[IOPLT-180] Add the Outlined variant on Badge component

---

example/src/pages/ListItem.tsx
src/components/listitems/ListItemNav.tsx

This PR adds the optional `iconColor` prop to the `ListItemNav` component. The `iconColor` prop will allow to set custom colors for the left icon int the list item.
- [src/components/listitems/ListItemNav.tsx](https://github.com/pagopa/io-app-design-system/compare/add-icon-color-prop-to-listitemnav?expand=1#diff-664aca5d6d72fd3f1bdccf1f4c3fa1003a011e367b5e0b8fd40c8aaa465bf32e): added `iconColor` prop with default `grey-450` color.
In the example app, navigate to the List Item section to see the new ListItemNav configuration at work.

chore: add `iconColor` prop to `ListItemNav`

---

example/src/pages/HeaderSecondLevel.tsx
src/components/layout/HeaderSecondLevel.tsx

Fixes the header background color when transparent mode is enabled
- Feature A
Check the HeaderSecondLevel page on example app add a background color to any element, header should cover it.

fix: HeaderSecondLevel background color don't covers safearea

---

src/components/textInput/TextInputBase.tsx

This PR fixes an issue on TextInput component preventing tap on the Label area
- Fixes TextInput components
Check Example app related page

fix: Restore TextInput tap events on Label area

---

example/src/pages/Buttons.tsx
src/components/buttons/ButtonLink.tsx

This PR adds the `contrast` variant to the `ButtonLink` component
- Add the missing `contrast` variant
2. Go to the **Buttons** page

Add `contrast` variant to `ButtonLink`

---

example/src/pages/HeaderFirstLevel.tsx
src/components/layout/HeaderFirstLevel.tsx

This PR changes `IconButton` color to `primary` in the `HeaderFirstLevel` component.
- As described in the short description
- Force title to be black (was `undefined`) in the light variant
| ![Simulator Screen Shot - iPhone 14 Pro - 2023-11-28 at 14 13 18](https://github.com/pagopa/io-app-design-system/assets/1255491/6471bc9b-0cb6-49a7-a270-c8ea51207a32) | ![Simulator Screen Shot - iPhone 14 Pro - 2023-11-28 at 14 12 28](https://github.com/pagopa/io-app-design-system/assets/1255491/c9828bf9-ca15-4319-ae6f-427ad59b96fb) | 
2. Go to the **Header First Level** screen

[IOAPPFD0-195] `HeaderFirstLevel` · Change `IconButton` color to `primary` (from `neutral`)

---

src/components/typography/LabelHeader.tsx

This PR fixes the condition which prevents the `LabelHeader` font style to be correctly handled in the experimental state
- Fixes `LabelHeader` experimental/legacy view
Check TabNavigation page on example app

fix: [IOPLT-303] LabelHeader experimental font style is inverted

---

src/components/listitems/ListItemHeader.tsx

This PR fixes the margin of the icon of the `ListItemHeader` component that is too wide.
| ![Simulator Screen Shot - iPhone 14 Pro - 2023-12-15 at 15 01 14](https://github.com/pagopa/io-app-design-system/assets/1255491/082e395c-e9d3-4bcf-ba82-18d810925fa4) | ![Simulator Screen Shot - iPhone 14 Pro - 2023-12-15 at 15 23 20](https://github.com/pagopa/io-app-design-system/assets/1255491/4cf373b0-db28-46cb-958a-72e8b358fcbd) | 
2. Go to the **List Items** page

[IOAPPFD0-203] Fix the margin of the icon of the `ListItemHeader` component that is too wide

---

example/src/pages/TabNavigation.tsx
src/components/tabs/TabItem.tsx

This PR adds the disabled variant to TabItem component
- TabItem color map statuses
- Example page for TabNavigation
Check the example app TabNavigation screen

[IOPLT-310] Adds disabled variant to TabItem

---

src/components/listitems/ListItemRadioWithAmount.tsx
src/components/listitems/__test__/__snapshots__/listitem.test.tsx.snap

This PR fixes the wrong color of `ListItemRadioWithAmount` label, caused by the incorrect declaration of the `useIOExperimentalDesign` hook
- Fix the declaration using the object destructuring syntax, from `const isExperimental` to `const { isExperimental }`
2. Go to the **Selection** page and look for `ListItemRadioWithAmount` (under **Radio** group)

[IOAPPFD0-204] Fix wrong color of `ListItemRadioWithAmount` label when new DS is turned off

---

example/src/pages/ListItem.tsx
src/components/listitems/ListItemNav.tsx

This PR adds the ListItemNav calendar variant
- ListItemNav
Check ListItems page on example app

[IOPLT-317] Adds ListItemNav Calendar version

---

src/components/featureInfo/FeatureInfo.tsx

This PR increases the font size in the `FeatureInfo` component.
- Change typographic styles (from default `14` font size to `16`)
| ![Simulator Screenshot - iPhone 14 Pro - 2024-01-22 at 15 16 39](https://github.com/pagopa/io-app-design-system/assets/1255491/e3fe32d7-2cd4-46b9-b10b-f3ae1b0849ab) | ![Simulator Screenshot - iPhone 14 Pro - 2024-01-22 at 15 16 05](https://github.com/pagopa/io-app-design-system/assets/1255491/a7a23ebc-93f9-4f1b-8c6d-02c67ac9fdd2) | 
1. Run the example app
2. Go to the **Advice & Banners** page

[IACROSS-214] Increase the font size of the `FeatureInfo` component

---

src/components/tag/Tag.tsx

This PR adds the accessibility label property for the icon of the `Tag` element.
- Added an optional string for the accessibility label that is forwarded to the the Icon component (that already supports accessbiility)

chore: added optional accessibility label for the icon on the Tag element

---

src/components/layout/HeaderSecondLevel.tsx

This PR disables accessibility on the title of the HeaderSecondLevel when the former is an trimmed empty string.
- Title's accessibility is disabled if the trimmed string is empty

[chore] Accessibility of empty Header Second Level's title

---

example/src/pages/ListItem.tsx
src/components/listitems/ListItemNav.tsx

This PR implements the loading status on the `ListItemNav` component showing an activity indicator spinner
- Added the boolean `loading` prop to the `ListItemNav`, showing an activity indicator spinner if set to true and if is a true value, the `onPress` event will not be fired.
https://github.com/pagopa/io-app-design-system/assets/34343582/a025ebe1-a162-4f8d-9922-4b9d76ba401b

chore: [IOBP-528] Added the loading status on `ListItemNav` component

---

example/src/pages/Modules.tsx
src/components/layout/HeaderSecondLevel.tsx
src/components/listitems/ListItemHeader.tsx
src/components/modules/ModuleAttachment.tsx
src/components/modules/index.tsx
stories/components/modules/ModuleAttachment.stories.ts

This PR add the ModuleAttachment component and fixes accessibility on Android for ListItemHeader
- Added ModuleAttachment
- ListItemHeader's label ignores accessibility on Android if the parent view is marked as accessibile (this avoid a double reading of such label - iOS is not affected)

[chore] Add ModuleAttachment, fix accessibility on ListItemHeader

---

src/components/buttons/ButtonOutline.tsx
src/components/buttons/ButtonSolid.tsx
src/components/buttons/__test__/__snapshots__/button.test.tsx.snap

This PR improves the accessibility behaviour on ButtonSolid and ButtonOutline on Android devices.
- On Android, TalkBack was reading a button's label twice. Its text part has been configured to be ignored.
- iOS already has the right behaviour, since it works by reading the `accessibility={true}` flag on the parent item and groups all its children together.

[chore] ButtonSolid and ButtonOutline accessibility on Android

---

example/src/pages/Selection.tsx
src/components/listitems/ListItemRadio.tsx
src/components/radio/RadioGroup.tsx

On RadioGroup component change type of description from `string` to `string | React.ReactNode` to accept ad JSX as description. 
- change type of description
- update example on example app 
Run the example app and navigate to the 'Selection' section. As you can see from the screenshoot, the item I added has the title "Let's try with JSX description".

[IOPID-1610] on RadioGroup component change type of description

---

src/components/buttons/ButtonLink.tsx
src/components/buttons/ButtonOutline.tsx
src/components/buttons/ButtonSolid.tsx
src/components/layout/BlockButtons.tsx

This PR adds the forwardRef definition to button components.
- Adds `React.forwardRef` definition to `ButtonSolid`, `ButtonOutline`, `ButtonLink`
Ref should be propagated without warnings.

chore: Add Ref prop to Button components

---

README.md
example/src/pages/Logos.tsx
example/src/pages/Selection.tsx
package.json
src/components/avatar/Avatar.tsx
src/components/avatar/__test__/__snapshots__/avatar.test.tsx.snap
src/components/checkbox/AnimatedMessageCheckbox.tsx
src/core/IOStyles.ts

This PR updates the `Avatar` component with an inner rounded wrapper to handle edge cases (entity logos without rounded shapes, etc...). It also deprecates the `shape` prop because the rounded square is the only accepted variant.
- Add two different radius values: `8` for small version, `12` for medium one
- Link the shape radius value to the `AnimatedMessageCheckbox` component
- Deprecate `shape` prop using JSDoc syntax
- **[Extra]** Add `react-native-easing-gradient` as peer dependency
https://github.com/pagopa/io-app-design-system/assets/1255491/5f33f7be-593a-4b21-a2b8-85f35ee485e1
2. Go to the **Logos** page

[IOAPPX-260] Update `Avatar` component, deprecate `shape` prop

---

src/components/listitems/ListItemInfoCopy.tsx
src/components/listitems/__test__/__snapshots__/listitem.test.tsx.snap

This PR fixes the accessibility on `ListItemInfoCopy` for Android.
- `no-hide-descendents` added on the child view of the `Pressable` component in the `ListItemInfoCopy`, in order to prevent the internal views to be read twice by the TalkBack

chore: Proper accessibility on ListItemInfoCopy on Android

---

example/src/App.tsx
example/src/pages/NumberPad.tsx
example/src/pages/Selection.tsx
src/components/checkbox/CheckboxLabel.tsx
src/components/layout/HeaderFirstLevel.tsx
src/components/listitems/ListItemCheckbox.tsx
src/components/listitems/ListItemRadio.tsx
src/components/listitems/ListItemRadioWithAmount.tsx
src/components/listitems/ListItemSwitch.tsx
src/components/listitems/__test__/__snapshots__/listitem.test.tsx.snap
src/components/radio/RadioButtonLabel.tsx
src/components/switch/SwitchLabel.tsx

This PR makes *Selection* components dark mode compatible.
- Add theme values to various `Radio`, `Checkbox` and `Switch` components
- Make `HeaderFirstLevel` dark mode compatible
2. Go to the *Selection* page, enable/disable dark mode

[IOAPPX-262] Make *Selection* components dark mode compatible

---

example/src/pages/StaticHeaderSecondLevel.tsx
src/components/layout/HeaderSecondLevel.tsx

This PR prevents accessibility focus on empty header title
- HeaderSecondLevel accessibility props
Test accessibility on real device to check TB/VO behaviour

fix: header accessibility on empty title should avoid autofocus

---

example/src/pages/ListItem.tsx
example/src/pages/Selection.tsx
src/components/listitems/ListItemNav.tsx
src/components/listitems/ListItemRadio.tsx

This PR introduces the possibility to set a remote image to the `ListItemNav` and `ListItemRadio` in order to show a payment logo dynamically
- Edited `ListItemRadio` with a new payment logo with a `uri` props
- Edited `ListItemNav` payment logo with the new one `paymentLogoUri` that accepts a URI to render the logo as icon

chore: [IOBP-583] Added payment logo uri to `ListItemNav` and `ListItemRadio`

---

example/src/pages/TextInputs.tsx
src/components/textInput/TextInputBase.tsx

added `autoFocus` prop to `TextInputBase` in order to be able to focus any text input on first render
- added prop
- added example app entry
in the example app, navigate to the text inputs section and make sure the second input has been automatically focused

[IOBP-576] TextInputBase autoFocus prop

---

example/src/pages/Logos.tsx
src/components/logos/LogoPaymentCard.tsx
stories/foundation/logos/LogoPaymentCard.stories.ts

This PR adds _a11y_ props to `LogoPaymentCard` in order to be used in the new `PaymentCard` component.
- Add mandatory `accessibilityLabel` prop
- Make the component always accessible
- Add optional `testID` prop
- Update relative Story
N/A

[IOAPPX-267] Add a11y props to `LogoPaymentCard`

---

src/components/textInput/TextInputBase.tsx

This PR fixes the wrong color of `TextFields` components when the experimental DS is disabled.
- Add the correct theme key value to the border
- Change caret color on both iOS and Android
| New DS off | New DS on |
| ![Simulator Screenshot - iPhone 14 Pro - 2024-03-27 at 10 07 20](https://github.com/pagopa/io-app-design-system/assets/1255491/2f4c4937-916d-406d-bdba-6b593ff01536) | ![Simulator Screenshot - iPhone 14 Pro - 2024-03-27 at 10 07 31](https://github.com/pagopa/io-app-design-system/assets/1255491/d5fe14c7-1584-4bbd-b2b3-0cf4712d469f) | 
2. Go to the **TextInputs** screen

[IOAPPX-269] Fix wrong color of TextInput when experimental DS is off

---

src/components/avatar/Avatar.tsx
stories/foundation/avatar/Avatar.stories.ts

This PR fixes a coding issue that would cause problem using Avatar component. 
`imageSource` prop was defined but actually unused, logoUri is the predefined one.
- Remove imageSource prop from Avatar.tsx
Check avatar component to proper render

fix: avatar component unused props

---

example/src/pages/ListItem.tsx
src/components/listitems/ListItemRadio.tsx

This PR fixes the aspect ratio for rectangular icons added to `ListItemRadio` components
- Added `resizeMode: "contain"` to `ListItemRadio` image
- Added examples
Navigate to **List Items > ListItemRadio**, check that the `ListItemRadio` with a square icon is displayed correctly like in the preview below.

[IOBP-600] Fix list item radio icon resize mode

---

example/src/pages/Modules.tsx
src/components/modules/ModuleCheckout.tsx

This PR adds the ability to use an external image as icon in the `ModuleCheckout` component
- Refactored `ModuleCheckoutProps`
- Added ability to pass an external URI (or internal asset) as image to `ModuleCheckout` component
Launch the example app and check the **Module** section. Component should render as the preview belo

chore: add image prop to `ModuleCheckout` component

---

src/components/listitems/ListItemSwitch.tsx

This PR adds the optional property testID to ListItemSwitch.
- ListItemSwitch’s props have the testID property
- ListItemSwitch’s main view uses the provided testID property, if defined, or fallback to default one

[chore] Add optional `testID` property to `ListItemSwitch`

---

example/src/pages/Badges.tsx
src/components/tag/Tag.tsx

This PR adds a new `Tag` variant that allows the passing of custom icon props such as icon name and icon color, making this component more flexible and dynamic as showed in the following case: https://www.figma.com/file/yOoBGDr1MJpa0LY5lDUFSd/IOapp_CartaGiovaniNazionale?type=design&node-id=4405-100552&mode=design&t=YXJlUj57xQtDYAm8-4
- Added a new variant name `customIcon`
- Added a new prop `customIconProps` which is required when the variant is `customIcon`

chore: [PE-578] Add new variant to the `Tag` component

---

src/components/listitems/ListItemNav.tsx

This PR adds the `numberOfLines` prop to the value of the `ListItemNav` component.
- added the `numberOfLines` prop

[IOPAE-1166] Add `numberOfLines` prop to `ListItemNav` component

---

src/components/listitems/ListItemHeader.tsx

This PR adds the header role to the label of the `ListItemHeader` component.
- Added `role` attribute to the `H6` component that wraps the label
With the voice over active, you should be able to hear the heading role while tapping on it.

chore: [IOBP-641] Add `ListItemHeader` a11y role as heading

---

example/src/pages/ListItem.tsx
src/components/listitems/ListItemInfo.tsx

This PR adds the ability to show a payment logo for the `ListItemInfo` component.
- Added prop `paymentLogoIcon` so that if it is added, the `icon` props should not be indicated.
- Added an example into the example app with a payment logo indicated
Run the example app and navigate through the List item section, you should be able to see a list item info that has a payment logo.
https://www.figma.com/design/SDaOSTsQnJUxmoPQEfz3bJ/Ricevuta-di-pagamento-pagoPA?node-id=501-7279&t=LEssmiht33qKZ8ls-4

chore: [IOBP-654] Add paymentLogoIcon attribute to the `ListItemInfo`

---

src/components/layout/HeaderSecondLevel.tsx

This PR adds the `backTestID` prop to the `Back` button in the `HeaderSecondLevel` component. This change is necessary because some `BaseScreenComponent` instances in `io-app` have this property for testing purposes.
- Add `backTestID` to the `HeaderSecondLevel`
N/A

[IOBP-653] Add `backTestID` to `HeaderSecondLevel`

---

src/components/listitems/ListItemRadio.tsx

add `importantForAccessibility="no-hide-descendants"` to read correctly on Android the accessibility label 
> [!Important]
> On iOS the accessibility was read correctly and there was no regression, so there is no video 
<p>
| 🤖 Android OLD 🤖 |🤖 Android NEW 🤖 |
| - | - |
| <video src="https://github.com/pagopa/io-app-design-system/assets/83651704/2853912f-0bba-42f9-94e0-c415efe1a9f5"/> | <video src="https://github.com/pagopa/io-app-design-system/assets/83651704/29c24245-7712-451b-8c3b-4985c0f6ddf1"/> |
</p>

[IOPID-1531] fix radio button accessibility on android

---

src/components/listitems/ListItemHeader.tsx

This PR fixes the wrong font weight in `ListItemHeader` when experimental DS is off.
**Before →** Titillium, regular font weight
**After →** Titillium, semibold font weight
- Remove `weight="regular"` prop that forced a regular font weight also in the typographic style (DS off)
N/A

[IOAPPX-312] Fix wrong font weight in `ListItemHeader` when experimental DS is off

---

src/components/badge/Badge.tsx
src/components/modules/ModuleAttachment.tsx
src/components/modules/ModuleCredential.tsx
src/components/modules/ModuleNavigation.tsx
src/components/modules/ModulePaymentNotice.tsx
src/components/typography/LabelSmall.tsx

This PR aligns the component used on ModulePaymentNotice and ModuleAttachment to the DS styles.
- ModulePaymentNotice: one-line, never-trimmed payment amount
- MouleAttachment: LabelSmallAlt instead of LabelSmall (Readex Pro instead of Titillium)
Check that both component have the proper styles.

[IOCOM-1394,IOCOM-1478] ModulePaymentNotice and ModuleAttachment fixes

---

example/src/pages/SearchCustom.tsx
package.json
src/components/searchInput/SearchInput.tsx

This PR adds `keepCancelVisible` prop on SearchInput component in order to keep the cancel button visible when the input loses focus.
2. Go to the **SearchCustom** screen

chore: Add `keepCancelVisible` prop on SearchInput

---

src/components/layout/HeaderSecondLevel.tsx

This PR fixes the `HeaderSecondLevel` UI regression, introduced by mistake with the following PR:
* https://github.com/pagopa/io-app-design-system/pull/285
The problem 
- Apply the `animatedStyle` in all the conditions
(Please look at the header's bottom border)
| <video src="https://github.com/pagopa/io-app-design-system/assets/1255491/cafdf95b-b4a4-4b5c-a316-21708a04c758" /> | <video src="https://github.com/pagopa/io-app-design-system/assets/1255491/96dc7c95-e658-4f12-95ff-e4b9efed3565" /> |  
2. Check out every example that's using `HeaderSecondLevel`

[IOAPPX-324] Fix `HeaderSecondLevel` UI regression

---

src/core/IOColors.ts

This PR enables the rendering of the legacy `blue` to `Pictogram` component, when experimental DS is off.
- Add relative theme key to `IOThemeLightLegacy`
https://github.com/pagopa/io-app-design-system/assets/1255491/638b6645-723a-4229-9957-69eae37d7aeb
2. Go to the **Pictograms** screen with DS enabled or disabled

[IOAPPX-331] Add legacy `blue` to `Pictogram`, when experimental DS is off

---

src/components/accordion/AccordionItem.tsx
src/components/modules/ModuleAttachment.tsx

This PR fixes the wrong chromatic values of the `AccordionItem` component
- Add theme-based keys to the component to fix the chevron set with hardcoded `blueIO-500` value
- Add (temporary) dark mode support
- **[extra]**: Fix wrong border color of `ModuleAttachment`
https://github.com/pagopa/io-app-design-system/assets/1255491/43b92dc7-570c-471d-bc3c-a4e0f5cb1517
1. Run the example app
2. Check **Accordion** screen

[IOAPPX-329] Fix chromatic values of the `AccordionItem` component

---

src/components/checkbox/AnimatedMessageCheckbox.tsx

This PR fixes computation of `isChecked` value on `AnimatedMessageCheckbox`
- When the input property is `undefined`, `isChecked` should have `false` value

[chore] Fix `isChecked` value on `AnimatedMessageCheckbox`

---

example/src/pages/Layout.tsx
src/components/stack/Stack.tsx
src/core/IOSpacing.ts

This PR adds the new optional `alignItems` prop to `HStack` and `VStack` components
- Add the new optional `alignItems` prop
2. Check the **Layout** screen

[IOAPPX-334] Add `alignItems` prop to `HStack` and `VStack` components

---

src/components/numberpad/__test__/__snapshots__/NumberPad.test.tsx.snap
src/components/typography/H3.tsx
src/components/typography/H4.tsx
src/components/typography/__test__/__snapshots__/typography.test.tsx.snap

This PR decreases `H4` and `H3` font sizes (legacy version only). This is necessary to avoid noticeable differences between the new and legacy versions of the same typographic style, especially on the new Services section.
- Decrease H4 font size
- Decrease H3 font size
N/A

Decrease `H4` and `H3` font sizes (legacy version)

---

src/components/typography/Label.tsx

This PR adds support for grey-700 color on Label.
- grey-700 added to allowedcolors on Label

[IOCOM-1600] Support for grey-700 on Label

---

src/components/listitems/ListItemAction.tsx
src/components/listitems/ListItemInfoCopy.tsx
src/components/listitems/ListItemNavAlert.tsx
src/components/listitems/__test__/__snapshots__/listitem.test.tsx.snap

This PR removes mandatory a11y props from some `ListItem…` components:
- `ListItemAction`
- `ListItemNavAlert`
- `ListItemInfoCopy`
N/A

[IOAPPX-359] Remove mandatory a11y props from some `ListItem…` components

---

src/components/typography/Label.tsx
src/components/typography/LabelMini.tsx
src/components/typography/LabelSmall.tsx
src/components/typography/__test__/__snapshots__/typography.test.tsx.snap
src/utils/fonts.ts

This PR fixes a number of issues that were encountered when adding `IOText` to the main repo
- Set `Label…` default weight to `Semibold`, instead of `Bold` → https://github.com/pagopa/io-app-design-system/commit/13819ba2ef5df2811bd7254c861020b8cf9d9cb4
- Fix wrong autocomplete of `IOText` when using `font` prop → https://github.com/pagopa/io-app-design-system/commit/6f1496c7235d32bf05b5256e62e87fcf38b1abb8
- Update `Label…` snapshots → https://github.com/pagopa/io-app-design-system/pull/322/commits/0ffdfcd8653afeb70069b3bf793b97e497f88af5
N/A

[IOAPPX-362] Change `Label…` default weight to Semibold + Fix autocomplete of `IOText` when using `font` prop 

---

src/components/toast/ToastProvider.tsx

This PR refines the `entering/exiting` transition by giving a smoother motion.
- Change transition configuration to both `entering` and `exiting` transitions
| <video src="https://github.com/user-attachments/assets/615eadcd-0f29-4f62-af10-c326e597f0f2" /> | <video src="https://github.com/user-attachments/assets/bd138cb4-cf14-42f2-a4a7-1743cb071916" /> | 
N/A

[IOAPPX-366] Refine `entering/exiting` transition applied to `ToastNotification`

---

src/components/badge/Badge.tsx
src/components/badge/__test__/__snapshots__/badge.test.tsx.snap
src/components/listitems/ListItemInfo.tsx
src/components/listitems/__test__/__snapshots__/listitem.test.tsx.snap

In this PR, the accessibility of the ListItem component has been improved, as well as the Badge component, which previously lacked accessibility handling.
<p>
| 🍏 A11Y iOS 🍏 | 🤖 A11Y Android 🤖 | 
| - | - |
| <video src="https://github.com/user-attachments/assets/a5d1ea0c-9567-40e5-a200-316201b6dd6c" /> | <video src="https://github.com/user-attachments/assets/9502b734-d2d7-4482-88b7-f903d92ce5c8" />  |
</p>
To test this functionality, you can try out the components in the test app.

[IOPID-2111] Fix `ListItemInfo` screen reader behaviour

---

src/components/badge/Badge.tsx

Change badge purple variant color
See https://pagopa.atlassian.net/browse/PE-680 for changes details
- changed color
- Login into app
- Go to CGN card trough wallet (add it to wallet if needed)
- "discover opportunities"
- select a catagery
- select a merchant
- the badge colors should be of a clearer purple color (it was so dark that it looked black before)

feat: [PE-680] Change purple badge colors

---

example/src/navigation/navigator.tsx
example/src/pages/HeaderSecondLevel.tsx
example/src/pages/HeaderSecondLevelDiscreteTransition.tsx
example/src/pages/HeaderSecondLevelForModal.tsx
example/src/pages/HeaderSecondLevelWithStepper.tsx
example/src/pages/StaticHeaderSecondLevel.tsx
src/components/layout/HeaderSecondLevel.tsx
src/core/IOColors.ts

This PR adds dark mode compatibility to the `HeaderSecondLevel`
- Replace previous default colors with new ones based on the theme
https://github.com/user-attachments/assets/5558dd78-beaf-4186-b09c-06681e61a28c
Launch the example app and visit each screen related to the **Header Second Level**

[IOAPPX-398] Add dark mode compatibility to `HeaderSecondLevel`

---

src/components/listitems/ListItemTransaction.tsx
src/core/IOColors.ts

This PR adds full dark mode support to `ListItemTransaction`.
Amount was previously rendered as black text:
Enable **Dark mode** on the **List Items** page of the example app

[IOAPPX-402] Add full dark mode support to `ListItemTransaction`

---

src/components/listitems/ListItemInfo.tsx

This PR introduces the accessibilityRole prop to the ListItemInfo component, enabling better support for accessibilty when displaying non-string values.
- Added `accessibiltyRole` prop to `ListItemInfo` component
1. Set the accessibilityRole prop on a ListItemInfo component.
2. Verify that screen readers correctly interpret the role specified by the prop, ensuring accessibility is enhanced as expected.

Add `accessibiltyRole` to `ListItemInfo` component

---

example/src/pages/HeaderSecondLevelCustomBackground.tsx
src/components/layout/HeaderSecondLevel.tsx

This PR removes the background opacity animation in `HeaderSecondLevel` component if the `transparent` prop is set to `false`
- set `headerBgColorTransparentState` color opacity only if `transparent` prop is set to `true`
Open the example app, check that the `HeaderSecondLevel` behaves as expected in every use case.

Remove `HeaderSecondLevel` background opacity animation if `transparent: false`

---

example/src/pages/NumberPad.tsx
src/components/codeInput/CodeInput.tsx

This PR fixes a visual regression introduced when [we increased the contrast of the `CodeInput` component](https://github.com/pagopa/io-app-design-system/pull/341).
- Change the color of the empty dot when we're using dark or accent backgrounds
- Make `CodeInput` dark mode compliant
https://github.com/user-attachments/assets/d436578e-98a7-4d5a-af7a-c45950bcecaa
Go to the **Number Pad** screen in the example app. Enable/disable accent background or enable/disable dark mode.

[IOAPPX-427] Fix `CodeInput` wrong empty colour when we're using dark or accent backgrounds

---

src/components/typography/IOText.tsx
src/utils/fonts.ts

This PR removes the TS constraints of the `size` property of the `IOText` component. It now accepts any numeric value.
- Change `IOText` TS requirements
N/A

[IOAPPX-438] Relax the TS constraints of `IOText` to accept any numeric value as `size`

---

src/components/layout/index.tsx

> [!caution]
> This PR depends on the approval of the following PR in the `io-app` repo:
> * https://github.com/pagopa/io-app/pull/6475
This PR removes the export of `BlockButtons` while waiting for the complete removal of the legacy `FooterWithButtons`.
N/A

[IOAPPX-444] Remove export of `BlockButtons`

---

src/components/banner/Banner.tsx
src/components/banner/__test__/__snapshots__/banner.test.tsx.snap

This PR restores `a11y` props in the `Banner` component, erroneously removed with the PR https://github.com/pagopa/io-app-design-system/pull/344

[IOAPPX-443] Restore `a11y` props in the `Banner` component

---

src/components/modules/ModuleCredential.tsx

This PR fixes the end component of the `ModuleCredential`, allowing to hide the "right chevron" icon when a badge configuration is provided
- Refactored `ModuleCredential` `endComponent`
Check that ModuleCredential is rendered correctly in the example app

fix: module credential end component

---

example/src/pages/ListItem.tsx
src/components/listitems/ListItemNav.tsx
src/components/listitems/ListItemTransaction.tsx
src/components/listitems/__test__/__snapshots__/listitem.test.tsx.snap

This PR improves `ListItemNav` and `ListItemTransaction` dynamic spacing after testing the components with larger text in the following PR:
* https://github.com/pagopa/io-app/pull/6561
- Remove extra space before chevron in the `ListItemNav`
- Disable dynamic spacing in the `ListItemTransaction` between amount and chevron
N/A

[IOAPPX-456] Improve `ListItemNav` and `ListItemTransaction` dynamic spacing

---

example/src/pages/Buttons.tsx
src/components/buttons/ButtonLink.tsx
src/components/buttons/__test__/__snapshots__/button.test.tsx.snap
src/components/typography/ButtonText.tsx

This PR adds `numberOfLines` and `textAlign` props to `ButtonLink`. This change is necessary to fix some issues when text is larger and the text is truncated (e.g. `Forgot unlock code` action [in this screen](https://github.com/pagopa/io-app/pull/6561#pullrequestreview-2515040276))
- Add the mentioned props to `ButtonLink`
- Update example app with this edge case
1. Run the example app
2. Go to the **Buttons** screen

Add `numberOfLines` and `textAlign` props to `ButtonLink`

---

src/components/numberpad/NumberButton.tsx
src/components/numberpad/__test__/__snapshots__/NumberPad.test.tsx.snap

This PR fixes the `NumberButton` off-centre alignment when text is larger.
- Replace `H3` with `IOText` without setting line height 
- Update `jest` snapshot
Larger and bolder text of the `NumberPad`
Enlarge the text using the system settings. Go to the **Numberpad** screen and check the different combinations of the font scale.

[IOAPPX-460] Fix `NumberButton` off-centre alignment when text is larger

---

src/components/searchInput/SearchInput.tsx

This PR fixes the flickering behaviour in the `SearchInput` on iOS.
- Replace `ButtonLink` with `IOText`
- ~~Slightly refactor the component using `reanimated` Shared Values~~
The visual issue before the fix:
https://github.com/user-attachments/assets/27b5458c-0705-4ac8-93e6-2863251c9287
2. Go to the **SearchInput** screen, after enabling bolder text on iOS

[IOAPPX-462] Fix flickering behaviour in the `SearchInput` on iOS

---

src/components/otpInput/OTPInput.tsx

Added the `secureTextEntry` property to the `TextInput` of the custom `OTPInput` component to obscure the keyboard in screenshots and screen recordings, in case the component is used in a context where such protection is enabled (e.g. using `react-native-screenshot-prevent` lib).
- Added `secureTextEntry` prop

Add `secureTextEntry` to the `OTPInput`'s `TextInput` component

---

example/src/pages/HeaderFirstLevel.tsx
src/components/layout/HeaderFirstLevel.tsx
stories/foundation/templates/HeaderFirstLevel.stories.ts

This PR refactors `HeaderFirstLevel`'s actions props with a dynamic type which allows to configure 0 to 3 actions.
- Replaced `firstAction`, `secondAction` and `thirdAction` with `actions`
Run the example app and go to the **Header First Level** page, test the header with different action configurations

refactor: `HeaderFirstLevel`'s actions prop refactoring

---

example/src/pages/Buttons.tsx
example/src/pages/HeaderSecondLevelScreenDiscreteTransitionCustomBg.tsx
src/components/buttons/IconButton.tsx
src/components/layout/HeaderSecondLevel.tsx
src/core/IOColors.ts

This PR fixes an issue that occurred when a certain variant was set to `HeaderSecondLevel` and dark mode was enabled.
After the recent introduction of dark mode support for `IconButton`, all icon buttons rendered with dark tones were automatically switched to light tones when dark mode was enabled. This behavior is welcome in most cases, but we have some specific app screens where we set a specific variant (e.g., always light or always dark) regarding the enabled color scheme. 
This is especially common when we set a custom background color. In these cases, if you explicitly set the `HeaderSecondLevel` to dark tones (`neutral` variant), the color was automatically switched to light tones when dark mode was enabled.
> [!note]
> The fix only applies to the new UI. Don't expect the fix to …

fix: [IOAPPX-478] Fix `HeaderSecondLevel` issue when variant is set explicitly and dark mode is enabled

---

src/components/layout/HeaderSecondLevel.tsx

This PR fixes a wrong Typescript type associated to the `HeaderSecondLevel` component
- Fix wrong type in the `HeaderSecondLevel`
N/A

[IOAPPX-480] Fix type in the `HeaderSecondLevel`

---

.github/workflows/release-storybook.yml

This pull request update the `upload-pages-artifact` action to `v3.0.1` as it fix the [deprecation of upload-artifact@v3
](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/)

ci: Update storybook `upload-pages-artifact@v3`

---

src/components/layout/HeaderSecondLevel.tsx

This pull request introduces an enhancement to the `HeaderSecondLevel` component to improve accessibility handling. The main change is the addition of an `ignoreAccessibilityCheck` prop, which allows screen readers to bypass focusing on the title when other elements are focused, such as when an input text field is throwing an error.
- Added `ignoreAccessibilityCheck` prop to `CommonProps` to control whether the title should be ignored by screen readers when other elements are focused.
N/A
That's an example of what this change is resolving (look at the screen reader):
https://github.com/user-attachments/assets/b9642dca-cc66-4b15-8555-8d294cdde862

refactor: [IOBP-1163] Apply ignore accessibility flag

---

.github/workflows/release-storybook.yml

This pull request updates the `deploy-pages` action from version (v2.0.4) to (v4.0.5)

ci: Update `deploy-pages` to `v4.0.5`

---

src/components/textInput/TextInputValidation.tsx

This PR fixes a regression of `TextInputValidation` that was erroneously introduced by changing the condition associated with `labelError`.
- Restore previous strict condition
Previously `TextInputValidation` showed the label error in the initial state because `isValid` was set to `undefined`. Verify that this behavior no longer occurs

[IOPLT-952] Fix `TextInputValidation` regression

---

src/components/tabs/TabItem.tsx
src/core/IOColors.ts

This PR refactors `TabItem` and add support for dark mode
- Simplify the internal logic by showing the _pill_ shape in the light variant even in the _default_ state
- Compared to the previous one, the component only scales when pressed and doesn't change the background color
- Add dark mode support for the component
- Replace `BodySmall` with `IOText` to fix Android wrong alignment
- Remove the unused `blueIO-450` tint
- Add a slight haptic feedback when pressed
https://github.com/user-attachments/assets/76867274-d81b-4391-a02f-3a80438db5ce
Launch the example app and go to the **Tab Navigation** screen. Test and play with the components placed there.

[IOAPPX-481] Refactor `TabItem` and add support for dark mode

---

.github/actions/setup/action.yml

This PR updates `actions/cache` to fix the errors in the PR workflow.

ci: [IOAPPX-483] Update `actions/cache` due to GitHb deprecation

---

src/components/banner/Banner.tsx
src/components/banner/__test__/__snapshots__/banner.test.tsx.snap

This pull request includes changes to improve the accessibility and functionality of the `Banner` component. 
- Replacing the `View` component with a `Pressable` component for better handling of user interactions.
- Feature B
- Using a real device 📱, go in a `Banner` section
- Turn on the TalkBack accessibility tool
- Ensure that action buttons are pressable and reachable using only the keyboard
| Old (unable to trigger with `Enter`) | New|
| <video src="https://github.com/user-attachments/assets/0bf69143-1203-450d-be03-89dcc35c83fc"/> | <video src="https://github.com/user-attachments/assets/936d55b0-1854-4996-bcea-d9b75dce7d26"/> |

refactor(Banner): `a11y` replace `View` with `Pressable`

---

src/components/textInput/TextInputValidation.tsx

This pull request includes changes to the `TextInputValidation` component to improve accessibility adding a new property for an accessibility error label to ensure that screen readers announce the correct error message.
- Add `accessibilityErrorLabel` in the `TextInputValidation` component's props.
- Modified the `announceForAccessibilityWithOptions` method to use `accessibilityErrorLabel` if provided, otherwise fallback to the default error message.
N/A

feat: apply custom accessibility error label

---

src/components/typography/markdown/MdH1.tsx
src/components/typography/markdown/MdH2.tsx
src/components/typography/markdown/MdH3.tsx
src/core/IOColors.ts

This PR improves the markdown related typographic styles and some styles associated to dark mode.
- Increase the `MdH2` size 
- Change weight of `MdH3` typographic style
- Increase contrast of `textBody-tertiary` in dark mode
- Make the fallback color darker than the current color
2. Look at the end of the **Typography** screen

chore: [IOPLT-973] Improve markdown related typographic styles

---

example/src/pages/TextInputs.tsx
src/components/textInput/TextInputValidation.tsx

This pull request introduces a new validation mode for the `TextInputValidation` component, enabling validation based on a trigger event
- Added a new `validationMode` prop to determine whether validation occurs on blur or when an external button is pressed. Refactored the component to use `forwardRef` and `useImperativeHandle` to expose the `validateInput` function to parent components
- Added a new `TextInputValidationOnContinue` component that uses the new `validationMode` prop to validate input when a "Continue" button is pressed. Updated the `TextInputs` page to include instances of this new component. 
- Go in `TextInputs`
- Review, test, and verify the functionality of the new `TextInputValidation` implementation.
https://github.com/user-attachments/assets/d905c8c6-16c5-415a-9c22-ff …

feat: support for `onBlur` and `onContinue` validation modes in `TextInputValidation` component

---

src/index.tsx

This PR exports `a11y` related hooks
- Export `useIOFontDynamicScale` and `useBoldTextEnabled` hooks
N/A

fix: [IOPLT-982] Export `a11y` related hooks

---

src/components/textInput/TextInputValidation.tsx

This PR fixes an import introduced in the following PR: https://github.com/pagopa/io-app-design-system/pull/410 importing the`TextInputValidationRefProps` type with a relative path.

fix: Import `TextInputValidationRefProps` with relative path

---

example/src/pages/HeaderFirstLevel.tsx
example/src/pages/Typography.tsx
src/components/layout/HeaderFirstLevel.tsx
src/components/typography/H2.tsx
src/components/typography/H3.tsx

This PR increases the size of the title in the `HeaderFirstLevel`
- Refactor `H2` and `H3` to allow/remove `Bold` weight
- Add `maxFontSizeMultiplier` to set a maximum size limit when larger text is enabled
- Update `Typography` page in the example app
N/A

chore: [IOAPPX-488] Increase title size in the `HeaderFirstLevel`

---

src/components/tabs/TabNavigation.tsx

This props is useful for the new IOScrollViewLargeHeaderWithList component
This pull request introduces changes to the `TabNavigation` to add an optional `excludePadding` prop. This prop allows the user to control whether padding is applied to the container
- Added an optional `excludePadding` property to the `TabNavigation` type.
- Updated the `contentContainerStyle` to conditionally apply padding based on the `excludePadding` prop.
N/A

refactor(Tab): Add prop to exclude padding in container

---

src/components/radio/RadioGroup.tsx

This PR adds the `accessibilityLabel` prop to the `RadioItem` type to handle a11y in the `RadioGroup` component
- Added `accessibilityLabel` prop to the `RadioItem` type

chore: [IOBP-1186] Add `accessibilityLabel` prop to `RadioItem` type component

---

src/components/listitems/ListItemRadioWithAmount.tsx
src/components/listitems/__test__/__snapshots__/listitem.test.tsx.snap

This pull request includes a change to the `ListItemRadioWithAmount` component to improve its accessibility by providing a default accessibility label 
- Added a `defaultAccessibilityLabel` that combines the `label`, `formattedAmountString`, and `suggestReason` if available, and used it as a fallback for `accessibilityLabel` when it's not provide
N/A

refactor: default hint for a11y label

---

example/src/pages/NumberPad.tsx
src/components/codeInput/CodeInput.tsx
src/components/numberpad/NumberButton.tsx
src/components/numberpad/NumberPad.tsx
stories/components/numberpad/NumberPad.stories.tsx

> [!note]
> To avoid confusion between light and dark mode, this PR introduces a breaking change:
> `dark` → `primary`
> `light` → `neutral`
This PR adds the dark mode version to the `NumberPad` component
- Change `variant` accepted values of the `NumberPad` and `CodeInput` components
- Add dark mode version to the `NumberButton` component
- Add haptic feedback when the citizen presses the `NumberButton`
https://github.com/user-attachments/assets/2005aed5-b4d9-4492-a30c-48b9163d1212
2. Go to the **Number Pad** page.
3. Enable/Disable primary background. Enable/Disable dark mode.

[IOPLT-968] Add dark mode version to `NumberPad` component

---

src/components/textInput/TextInputBase.tsx

This pull request fixes the issue where the `counterLimit` was not correctly accounting for the spaces added by the `valueFormat` function in the `TextInputBase` component. This ensures that the actual text length (excluding spaces) is compared against the `counterLimit`.
- Updated the `onChangeTextHandler` to correctly handle the `counterLimit` by calculating the actual text length without spaces
- Adjusted the `maxLength` prop of the `TextInput` component to account for the spaces added by the `valueFormat` function
- Ensured that the `counterLimit` is respected correctly for formatted text inputs such as `credit-card` and `iban`
- Set a `counterLimit` in `DSTextFields`
- Insert some value in `credit-card` and `iban` `TextInput`
- Ensure that now the `counterLimit` displaying the …

fix(`TextInputBase`): correct counter limit handling

---

example/src/pages/ListItem.tsx
example/src/pages/Modules.tsx
example/src/pages/Selection.tsx
src/components/listitems/ListItemRadio.tsx
src/components/listitems/ListItemTransaction.tsx
src/components/listitems/__test__/__snapshots__/listitem.test.tsx.snap
src/components/modules/ModuleAttachment.tsx
src/components/modules/ModuleCheckout.tsx
src/components/modules/ModuleCredential.tsx
src/components/modules/ModuleNavigation.tsx
src/components/modules/ModulePaymentNotice.tsx
src/components/modules/ModuleStatic.tsx

This PR adds the proper accessibility state to all the components in the loading state
- Add `accessibilityState: { busy: true }` to all the components in the loading state 
- Add an optional `loadingAccessibilityLabel` prop to add a custom text while the component is in this state
- Update pages in the example app to reflect the mentioned changes
Use the screen reader and point to all components in the loading state. Previously, they were simply ignored.

fix: [IOPLT-1026] Add the proper accessibility state to all components in the loading state

---

example/src/pages/Advice.tsx
src/components/banner/Banner.tsx
src/components/featureInfo/FeatureInfo.tsx
src/components/typography/Body.tsx
src/components/typography/BodySmall.tsx
src/components/typography/IOText.tsx
src/components/typography/LabelMini.tsx

This PR adds an alternative `accessibilityRole` to `Banner`, `FeatureInfo` and all the typographic styles with the `asLink` prop.
- Add possible alternative `button` accessibility role to all the typographic styles with the `asLink` prop
- Add possibile alternative `button` accessibility role to `FeatureInfo`
- Add possibile alternative `link` accessibility role to `Banner`
Run the example app and try to edit these components with custom `accessibilityRole`

fix: [IOPLT-1028] Add alternative `accessibilityRole` to `Banner`, `FeatureInfo` and all the `asLink` typographic styles

---

src/components/modules/ModuleCheckout.tsx

This pull request adds an `accessibilityLabel` to the `ModuleCheckout` component to improve screen reader interaction, ensuring that the `CTA` text is announced correctly on Android, which was previously missing.
- Add an `accessibilityLabel` to the `PressableModuleBase` component to enhance screen reader support by including the `title` and `ctaText` properties.
- Enable TalkBack on Android or VoiceOver on iOS
- Navigate over a `ModuleCheckout` component
- Ensure that both Android and iOS correctly announce the `text` and `cta` if present

chore: adjust `ModuleCheckout` a11y label

---

src/components/otpInput/BoxedInput.tsx
src/components/otpInput/OTPInput.tsx
src/core/IOColors.ts

This PR adds dark mode support to `OTPInput`
- Add relative theme keys to the `IOTheme` object
- Slightly refactor `OTPInput` and `BoxedInput` to add theme keys
https://github.com/user-attachments/assets/c76e67b4-0c29-4e79-b944-6e366d395b79
Run the example app and go to the **OTPInput** page. Enable/disable dark mode for testing purposes.

chore: [IOPLT-967] Add dark mode support to `OTPInput`

---

src/components/typography/Body.tsx
src/components/typography/BodySmall.tsx
src/components/typography/LabelMini.tsx

This PR adds the text style property to Body, BodySmall and LabelMini, when configured as a link.
- text style when Body, BodySmall or LabelMini are used asLink
CI should succeed.

chore: [IOCOM-2160] Custom text style for BodySmall

---

src/components/avatar/Avatar.tsx
src/components/avatar/__test__/__snapshots__/avatar.test.tsx.snap

This PR restores previous `AvatarSearch` logic to avoid unexpected behavior in search results, due to `FlashList` optimisation techniques.
- Remove `useState` and `onError` function
For testing purposes, please refer to the previous merged PR:
- https://github.com/pagopa/io-app-design-system/pull/447

fix: [IOPLT-1049] Restore previous `AvatarSearch` logic to avoid unexpected behavior in search results

---

src/components/claimsSelector/__test__/__snapshots__/ClaimsSelector.test.tsx.snap
src/hooks/useAccordionAnimation.tsx

This PR fixes a visual bug that occurred in certain cases where content wasn't rendered at 100% of the available width.
- Add `width: 100%` to the body accordion container
- Update tests
https://github.com/user-attachments/assets/56089599-5e00-43d5-b3cf-e037f2146ea1
n/a

fix: [IOPLT-1084] Fix visual bug in the `AccordionItem`

---

example/src/pages/ListItem.tsx
src/components/listitems/ListItemInfo.tsx

This PR adds the possibility to render `ListItemInfo` without a label
- Label is now optional
- Fixed the accessibility label when the label is not available
Navigate to the list item info example component and check that everything works as intended without regressions

feat: [SIW-2213] allow ListItemInfo to render without a label

---

src/components/contentWrapper/ContentWrapper.tsx

This PR makes `ContentWrapper` less restrictive in terms of accepted props. In fact, it now accepts all `View` props except for some styles already managed by the component itself.
- Update `ContentWrapper` with the new TS configuration
N/A

chore: [IOPLT-1103] Make `ContentWrapper` less restrictive in terms of accepted props

---

src/components/alert/Alert.tsx

This PR fixes a glitchy behavior of the `Alert` component, probably caused by the different rendering of margins and content alignment when the text was rendered on a single line or on multiple lines. The glitchy behavior occurred for a rare combination of scaled font size and a certain number of characters at the edge of the two scenarios.
- Remove the `multiLine` condition
- To avoid wrong vertical alignment of the text, make the icon vertically centred in all cases
1. Go to the **Alert** page in the example app
2. Increase/decrease the font scale using Accessibility Inspector or your system settings

fix: [IOPLT-1110] Fix glitchy behavior of `Alert` under certain conditions

---

src/components/buttons/IOButton/IOButton.tsx
src/components/buttons/IOButton/__test__/__snapshots__/IOButton.test.tsx.snap

This pull request includes a minor change to the `IOButton` component that adds a default foreground color when button is disabled
This seems to solved the wrong button color for https://github.com/pagopa/io-app/pull/6750#issuecomment-2879310599
IOButton should work as before

fix: add button default color on disabled

---

src/components/searchInput/SearchInput.tsx

> [!important]
> This PR addresses an undesirable behavior that emerged in the following PR:
> * https://github.com/pagopa/io-app/pull/6934
This PR improves the `SearchInput` visual appearance when the citizen increased the text size. This change is applied to both iOS and Android versions.
- Remove fixed height
- Add specific `textAlignVertical` property for Android to center the input text
- Increase/Decrease text size, check `SearchInput` component in both iOS and Android

fix: [IOPLT-1138] Improve `SearchInput` visual appearance when text size is larger

---

src/components/typography/Body.tsx
src/components/typography/IOText.tsx

This PR removes the pressable wrapper on Body text component to solve a dynamic font sizing issue on the markdown render.
- adds the avoidPressable prop onto Typographic additional props
Check the render of body text nothing should be changed except from the usage of the prop.

fix: [IOPLT-1311] Removes pressable wrapper for markdown renderer integration

---

src/components/typography/BodySmall.tsx

This PR complements #491 to fix the same issue in the `BodySmall` component.
-  Integrate the new `avoidPressable` prop in `BodySmall`
Check the render of small body text: nothing should be changed except from the usage of the prop.

fix: [SIW-3075] Remove pressable wrapper from `BodySmall` for markdown renderer integration
